
version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout

      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      
      - run: npm test

      - run:
        name: Building
        command: |
          if [ "${CIRCLE_BRANCH}" == "staging" ]; then
          npm run build-qa
          elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build-prod
          else
              npm run build-dev
          fi

      - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - dist


  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
        - run:
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}
        - restore_cache:
            key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: Install aws cli
            command:
                sudo apt-get -y -qq install awscli
        # Set the signature version for the S3 auth
        - run:
            name: Setting Signature Version 4 for S3 Request Authentication
            command: aws configure set default.s3.signature_version s3v4
        # Deploy to the S3 bucket corresponding to the current branch
        - run:
            name: Deploy to S3
            command: |
                if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                    aws --region us-east-1 s3 sync dist s3://dev.cryptonerdclub.com/ --delete
                elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                    aws --region us-east-1 s3 sync dist s3://qa.cryptonerdclub.com/ --delete
                elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                    aws --region us-east-1 s3 sync dist s3://cryptonerdclub.com/ --delete
                fi


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
